name: Xcode - Build and Analyze

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'DBDebugToolkit/**'
      - 'Example/**'
      - '.github/workflows/**'
      - 'Package.swift'
      - 'DBDebugToolkit.podspec'
jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CocoaPod Install
        run: pod install
      - name: Build
        run: xcodebuild build -workspace DBDebugToolkit.xcworkspace -scheme DBDebugToolkit-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12,OS=15.3"
